import { Flashcard, LearningProgress } from '../lib/types';

export const mockFlashcards: Flashcard[] = [
  {
    id: 'fc-1',
    title: 'Compound Interest',
    category: 'Investing',
    definition: 'Interest earned on both the principal and accumulated interest from previous periods.',
    example: 'Invest $1,000 at 7% annually: Year 1 = $1,070, Year 2 = $1,145 (earning interest on interest)',
    whyItMatters: 'Often called the eighth wonder of the world, compound interest dramatically amplifies wealth over long periods.',
    commonMisconceptions: 'Compound interest only applies to investments. It takes decades to see meaningful returns.',
    reviewCount: 3,
    createdAt: '2024-01-15',
    updatedAt: '2024-07-20',
  },
  {
    id: 'fc-2',
    title: 'Diversification',
    category: 'Investing',
    definition: 'Spreading investments across different asset classes, sectors, or geographies to reduce risk.',
    example: 'Instead of putting $10,000 in one stock, allocate across US equities, bonds, international stocks, and real estate.',
    whyItMatters: 'Reduces portfolio volatility by avoiding concentration in one asset that could decline significantly.',
    commonMisconceptions: 'Owning many stocks in one sector is enough diversification. Diversification eliminates all risk.',
    reviewCount: 1,
    createdAt: '2024-02-10',
    updatedAt: '2024-07-19',
  },
  {
    id: 'fc-3',
    title: 'Dollar-Cost Averaging',
    category: 'Investing',
    definition: 'Investing a fixed amount of money at regular intervals regardless of market price.',
    example: 'Invest $500 every month into an S&P 500 index fund, regardless of whether prices are high or low.',
    whyItMatters: 'Removes emotion from investing and may reduce the impact of market volatility on average purchase price.',
    commonMisconceptions: 'DCA guarantees profit. It only works for stocks.',
    reviewCount: 0,
    createdAt: '2024-03-05',
    updatedAt: '2024-07-18',
  },
  {
    id: 'fc-4',
    title: 'Budget Allocation (50/30/20)',
    category: 'Budgeting',
    definition: 'A budgeting framework allocating 50% to needs, 30% to wants, and 20% to savings/debt payoff.',
    example: 'On a $5,000 monthly income: $2,500 needs, $1,500 wants, $1,000 savings.',
    whyItMatters: 'Provides a simple, flexible structure that balances spending with financial goals.',
    commonMisconceptions: 'The ratio must be exact. It works the same for everyone.',
    reviewCount: 2,
    createdAt: '2024-02-20',
    updatedAt: '2024-07-20',
  },
  {
    id: 'fc-5',
    title: 'Emergency Fund',
    category: 'Budgeting',
    definition: 'A savings fund covering 3-6 months of living expenses for unexpected financial hardships.',
    example: 'If monthly expenses are $3,000, aim for $9,000-$18,000 in liquid savings.',
    whyItMatters: 'Prevents relying on high-interest debt when unexpected expenses arise.',
    commonMisconceptions: 'Six months is required for everyone. Emergency funds should earn investment returns.',
    reviewCount: 1,
    createdAt: '2024-01-30',
    updatedAt: '2024-07-17',
  },
  {
    id: 'fc-6',
    title: 'Credit Score Components',
    category: 'Credit & Debt',
    definition: 'Payment history (35%), credit utilization (30%), age of accounts (15%), credit mix (10%), new inquiries (10%).',
    example: 'A score of 750+ typically qualifies for lower interest rates on mortgages and auto loans.',
    whyItMatters: 'Your credit score determines your borrowing costs and affects access to financial products.',
    commonMisconceptions: 'Checking your credit score hurts it. A single missed payment destroys your score.',
    reviewCount: 0,
    createdAt: '2024-03-12',
    updatedAt: '2024-07-16',
  },
];

export const mockProgress: LearningProgress = {
  flashcardsReviewed: 3,
  flashcardsTotal: 6,
  articlesRead: 12,
  videosWatched: 5,
  podcastsListened: 3,
  bookmarksCount: 8,
  favoritesCount: 4,
};
